### ISSUE TITLE
\providefontfamily に対応する \providejfontfamily

### ISSUE THREAD

**Issue by yuishin-kikuchi** [luatexja/luatexja#10]
fontspecでは \providefontfamily が提供されていますが、
luatexja-fontspecでは \provicejfontfamily が実装されていないことに気が付きました。
これは意図があって実装していないのでしょうか？

**Comment by h-kitagawa** [comment]
fontspec v2.7b (2019-02-12) で追加されていたのを今まで気づかなかっただけです^^;．時間のあるときに加えておきます．

**Comment by h-kitagawa** [comment]
[20240714.0](https://github.com/luatexja/luatexja/releases/tag/20240714.0) を出したので，完了とします．
