### ISSUE TITLE
表で `siunitx` を使用する際のクラッシュ

### ISSUE THREAD

**Issue by zyoshoka** [luatexja/luatexja#11]
[`latex-tools`](https://ctan.org/pkg/latex-tools) を最新版（revision: 71408）に更新すると、次のコード
```tex
\documentclass{ltjsarticle}
\usepackage{siunitx}
\begin{document}
\begin{tabular}{S}
  1
\end{tabular}
\end{document}
```
をコンパイルしようとした際に次のようなエラーが出ます。
```
Runaway argument?
\ignorespaces 1 \end {tabular} \end {document} 
! File ended while scanning use of \__siunitx_table_collect_begin:w.
<inserted text> 
\par 
```

上述のコードで `ltjsarticle` を `article` にするとコンパイルが通るので `luatexja` が原因かと思いこちらに報告させていただきましたが、もし原因が別のものによるものでしたらお手数ですがクローズのほどお願いします。

**Comment by h-kitagawa** [comment]
調査する時間がとれておらずすみません．とりあえず症状は確認しました．やっぱり LuaTeX-ja が原因っぽいですが，調べてみます

**Comment by zyoshoka** [comment]
迅速なご対応ありがとうございます。手元で試したところ正常にコンパイルできました。
