### ISSUE TITLE
jpotf "feature" が機能していない

### ISSUE THREAD

**Issue by h20y6m** [luatexja/luatexja#12]
jpotf "feature" が機能していないようです。

LuaTeX-ja のマニュアル 36 ページの図でも確認できます。

![image](https://github.com/luatexja/luatexja/assets/57307205/7bc70842-3c66-4e80-9ed3-380578d643f6)

---

デバックしてみたところ `vform` には想定される置換が入っているように見えますが、
以下の `vform` を使っているところの添え字 `pc` が未定義？のように見えます。

https://github.com/luatexja/luatexja/blob/7f860e25d88bf009b40ff6ce6652c8c05f8df03e/src/ltj-pretreat.lua#L161

**Comment by h-kitagawa** [comment]
コメントが遅くなりましたが，https://github.com/luatexja/luatexja/commit/31e8fcdac216548a04560af33e9fce1cde31cfe4 の変更ではどうでしょうか．

**Comment by h20y6m** [comment]
直っているようです。ありがとうございました。
