### ISSUE TITLE
table tagging が機能しない

### ISSUE THREAD

**Issue by h-kitagawa** [luatexja/luatexja#13]
see https://github.com/latex3/tagging-project/issues/87

**Comment by h-kitagawa** [comment]
備忘録：lltjext.sty のコードは要検討．tagging の際には array パッケージが自動で読み込まれることも考慮が必要．

**Comment by FrankMittelbach** [comment]
Great, thanks. It is wonderfull to see how we make progress in getting nicely tagged output more and more!
