### ISSUE TITLE
（機能要求）組方向を判断するif文インターフェイス

### ISSUE THREAD

**Issue by yuishin-kikuchi** [luatexja/luatexja#15]
連続の要望となってしまい申し訳ないです。

私のわがままにお答えいただ提案をもとに
リガチャを作っていて思ったのですが、
リガチャって場合によっては横組み用と縦組み用で切り替える必要がありますよね。
「オントロ・グスーム」問題（オングストロームの2文字幅にわたったリガチャ）のように……
でも、コードの可読性から考えると同一のコマンドで対応したい。

そこで、ifmmodeのように使える
\ifyoko, \iftate, \ifdtou, \ifutod
がインターフェイスとして提供されてもよいのではないかと思いました。

これはluatexja-adjustですかね？

**Comment by h-kitagawa** [comment]
[マニュアル](https://github.com/luatexja/luatexja/blob/master/doc/luatexja-ja.pdf) pp. 28--29 に記述があります．

| 働き | pTeX | LuaTeX-ja |
|---|---|---|
| 現在が横組か判定 | `\ifydir ...\fi` | `\ifnum\ltjgetparameter{direction}=4 ... \fi` |
| `\box 900` の内容が横組か判定 | `\ifybox900 ...\fi` | `\ifnum\ltjgetparameter{boxdir}{900}=4 ... \fi` |
| 現在が縦組か判定 | `\iftdir ...\fi` | `\ifnum\numexpr\ltjgetparameter{direction}-(\ltjgetparameter{direction}/8)*8=3  ... \fi` |
| 現在が dtou 方向か判定 | `\ifddir ...\fi` | `\ifnum\ltjgetparameter{direction}=1 ... \fi` |

縦組だけ煩雑になっているのは，pTeX の `\iftdir` では通常の縦組と「縦数式ディレクション」（LuaTeX-ja で言うところの utod 方向）の両方が真になるためです（pTeX マニュアル  4.3 節参照）．縦数式ディレクションのことを考えなくて済むのなら
```
\ifnum\ltjgetparameter{direction}=3 ... \fi
```
でいいです．

使用例は，ltjsarticle.cls にあります：
```
\def\pltx@today@year@#1{%
  \ifnum\numexpr\year-#1=1 元\else
    \ifnum\ltjgetparameter{direction}=3
      \kansuji\numexpr\year-#1\relax
    \else
      \number\numexpr\year-#1\relax\nobreak
    \fi
  \fi 年
}
```
派生元の jsarticle.cls の
```
\def\pltx@today@year@#1{%
  \ifnum\numexpr\year-#1=1 元\else
    \ifnum1=\iftdir\ifmdir0\else1\fi\else0\fi
      \kansuji\numexpr\year-#1\relax
    \else
      \number\numexpr\year-#1\relax\nobreak
    \fi
  \fi 年
}
```
と比較してください．

**Comment by yuishin-kikuchi** [comment]
これは失礼しました。
つい数分前にluatexjaのマニュアルを見て「あれ……？」と
思って謝ろうと思っていたところ、先に回答されていました。

もっとマニュアルをきちんと読みます。
これは反省だ。
