### ISSUE TITLE
（機能要求）LuaTeX-jaに問題なく対応できる下線スタイルファイル

### ISSUE THREAD

**Issue by yuishin-kikuchi** [luatexja/luatexja#16]
わがままの連続となってしまい申し訳ないです。
lua-ulというパッケージがあります。
LuaLaTeXで改行に対応する下線またはハイライトを引けるというものです。

しかし、これを使って下線を引くと、きれいルビ周りの下線が消えます。
pxrubricaでもluatexja-rubyでもアウトでした。
よく検証したところ、unhbox と unvbox に対応しておらず、
このことを lua-ul 作者にバグとして報告したのですが、
バグと認めただけで半年以上経過し、まったく対応する気配がありません。
英語圏ではルビとかいうものはありませんからねぇ……

それどころか、教えていただいたluatexja-adjustをロードしたら
あさっての方向に下線が引かれてしまいました。
これがリクエストにつながります。

ルビ周りの下線が消えてしまうのでは話にならないので、
以前、uline--をLuaTeX-ja向けに調整して使おうとしたのですが、
数式のハイライトを試みるとクラッシュしました。
また、pxrubricaの \truby（上下にルビをつけるコマンド）
を使うにはさらに調整が必要という……

まあ、ifmmodeでuline--のコマンドとlua-ulのコマンドを切り替えれば、
一応の実現は可能っぽいです。
でも、普通に考えて

```$\myunderline{f(x)=x^2}$```

ではなく

```\myunderline{$f(x)=x^2$}```

と書きたいですよね。

だいぶわがままな要求とは理解していますが、
luatexja-ulなるパッケージを作ることはできないでしょうか。
細かいインターフェイスについては uline-- を踏襲するとよいかもしれません。
pLaTeX時代は「TeXは下線処理が苦手なんだからわがまま言うな」と一蹴される要求でしたが、
下線を引きたがっている人、けっこういるみたいです。

**Comment by h-kitagawa** [comment]
> lua-ul 作者にバグとして報告

https://github.com/zauguin/luaul/issues/18 ですね．
私も（太字と併用して）波線をよく使いますが，「せっかく lua-ul というパッケージがあるのだから，なんとかそれに乗っかる」方がよいと考えています．

> しかし、これを使って下線を引くと、きれいルビ周りの下線が消えます。
> pxrubricaでもluatexja-rubyでもアウトでした。

ルビまわりの下線が消えることは確認しましたが，[「質問のしかた」(TeX Wiki)](https://texwiki.texjp.org/?%E8%B3%AA%E5%95%8F%E3%81%AE%E3%81%97%E3%81%8B%E3%81%9F) にもあるように，再現する例を貼っていただけますか？

とくに，「luatexja-adjust であさっての方向に」というのが何をさすのかよくわかりません．

**Comment by h-kitagawa** [comment]
ここ数日試しているところです（一番新しいものは https://github.com/luatexja/luatexja/commit/a8f047f6cbfecdd973130916f575f9c8dd91cd5d）．

和文処理グルー周りは詰められていないところもありますが，前や後に約物類が来ない場合はなんとかなっている気がしています．

**Comment by h-kitagawa** [comment]
悩んでいるのが，「ルビの方が親文字より長く，前後の文字との間に空白が入る」かつ「下線がそのルビで始まる or 終わる」際に，空白に下線をかけるべきか，という点です．
`\underLine` も `\highLight` も状況は同じなので下の図は `\highLight` で作っていますが，図中の 1. と 2. のどちらにするのが「自然」なのでしょうか[^a]．
![grim2](https://github.com/user-attachments/assets/e4bd66ab-229f-4a64-a889-3adc9565b41b)

[^a]: 「）と◇」「◇と（」の間にはどっちみち半角の JFM グルーが入ります．これらには図中の 1. においても `\highLight` の有効範囲にはしていません．

**Comment by h-kitagawa** [comment]
[20240909.0](https://github.com/luatexja/luatexja/releases/tag/20240909.0) を CTAN にアップロードしました．luatexja-adjust がある状態でどうなるかはまだ試していませんが，そうでないときは対応できたと思います．
ここでクローズしますが，なにかあったときには再オープンしてください．
