### ISSUE TITLE
段落最終文字についての end_adjust

### ISSUE THREAD

**Issue by h-kitagawa** [luatexja/luatexja#22]
元報告は https://okumuralab.org/tex/mod/forum/discuss.php?d=3830 ．
段落末尾で句点ぶら下げになるべきところが，実際にはそうならずに，（句点の直前の数文字ごと）次の行に送られてしまう，という症状です．

原因の推測：
* luatexja-adjust の「行末文字の調整」が有効の場合，行分割時に考慮する (`lineend=extended`) か否か (`lineend=true`) どちらの設定になっているかに関係なく，**最終行については行分割後に**行末文字の位置調整を行う．
* したがって，行分割の時点では，段落最後にある句点について「ぶら下げ組という句点の幅を見かけ 0 にする」状況は考慮されず，半角幅を占めるものと扱われる．そのため，段落末尾の句点は（通常の行分割処理のように）次の行に送られてしまう．

**Comment by abenori** [comment]
単なる引用ですがこちらも同じですね． https://github.com/abenori/jlreq/issues/105

**Comment by h-kitagawa** [comment]
https://github.com/luatexja/luatexja/commit/5e51bfeca24c731145a6f14a187cf1201851c896 で，[TeX フォーラムの元記事](https://okumuralab.org/tex/mod/forum/discuss.php?d=3830)と abenori/jlreq#105 のテストソースが意図通りに動くようになりました．
