### ISSUE TITLE
defaultjfontfeaturesを使用できない

### ISSUE THREAD

**Issue by yuishin-kikuchi** [luatexja/luatexja#4]
LuaHBTeX, Version 1.17.0 (TeX Live 2023)(format=lualatex 2024.2.18)
luatexja-fontspec 2020-09-14

```latex
\documentclass[a4paper,11pt]{ltjsarticle}
\usepackage{luatexja-fontspec}
\defaultjfontfeatures[MicrosoftMincho]{
  UprightFont=msmincho,
}
\setmainjfont{MicrosoftMincho}
\begin{document}
どんなテキストでもよい
\end{document}
```

\defaultjfontfeatures を用いたとき、\l__ltj_fontspec_tmp_prop が undefined となる問題が生じるようになりました。
似た事象が他パッケージでも確認されており、l3kernelのアップデートと関連がありそうです。

**Comment by h-kitagawa** [comment]
確認しました．差分 https://github.com/luatexja/luatexja/compare/64ed97c...5199bdc に示したように luatexja-fontspec-27c.sty を更新するとどうなりますでしょうか．

**Comment by h-kitagawa** [comment]
https://github.com/luatexja/luatexja/releases/tag/20240219.0 を出したので，完了にします．
