### ISSUE TITLE
TikZ spyライブラリ使用時の不具合

### ISSUE THREAD

**Issue by earthoul** [luatexja/luatexja#5]
# 問題
Ti*k*Z `spy`ライブラリの`\spy`を使用する際、パッケージ読み込み順を変えたりBeamerにしたりするとビルドが失敗するようです。

TeX Live version 2024; packages up to date

# MWE

プリアンブルは下記成功例・失敗例にて

```latex
<プリアンブル>

\begin{document}

% tikz p.835 spy用例集より
\usetikzlibrary{decorations.fractals,spy}
\begin{tikzpicture}[
    spy using overlays={
      circle,
      magnification=3,
      size=1cm,
      connect spies
    }]
  \draw[decoration=Koch curve type 1]
    decorate{
      decorate{
        decorate{ (0,0) -- (2,0) }
      }
    };
  \spy[green] on (1.6, 0.3) in node at (3, 1);
\end{tikzpicture}

\end{document}
```

# ビルド成功例

```latex
\documentclass{ltjarticle}
\usepackage{tikz}
```

```latex
\documentclass{article}
\usepackage{luatexja}
\usepackage{tikz}
```

# ビルド失敗例

エラー表示は`! Missing number, treated as zero.`:

```latex
\documentclass{article}
\usepackage{tikz}
\usepackage{luatexja}
```

```latex
\documentclass[luatex]{beamer}
\usepackage{luatexja}
\usepackage{tikz}
```

```latex
\documentclass[luatex]{beamer}
\usepackage{tikz}
\usepackage{luatexja}
```

**Comment by h-kitagawa** [comment]
確認しました．
直接的には pgf/tikz の `\pgfsys@strcmp` の「中身」が LuaTeX-ja によって上書きされてしまった，ということなのです．ただ，私の感覚では，pgf/tikz か LaTeX がなんとかしてほしいなあ，という考えです．

----
以下，事情です．

TeX から Lua の関数 `fn()` を呼び出すとき，LuaTeX Reference manual の 2.4.4 節にあるように，次のようにするとオーバーヘッドを削減させることができます（n は番号です）：
 1.  `(lua.get_functions_tabl())[n] = fn` と関数を格納し
 2.  TeX 側で「`\luadef\CS 'n」とする（もしくは Lua 側で`token.set_lua("CS", n)`）と，以後 `\CS` で `fn()` が実行できる．

もちろん，n の値は重複してはいけません．後で`(lua.get_functions_tabl())[n] = fnX`とすると，それ以降で `\CS` で実行される関数が `fn()` でなく `fnX()` になってしまいます．

最近の LaTeX では \newluafunction によって「n の値の重複」を防ぐことができます．
```
% code A
\newluafunction\CS@@inner % 新しい番号を確保
\directlua{
  local t = lua.get_functions_table(); t[\the\CS@@inner]=fn
}
\luadef\CS \CS@@inner
```
LuaTeX-ja では，\luadef まわりをこの方法によって使っています．

しかし，前段落の方法は，pgfsys.code.tex で`\pgfsys@strcmp` の定義に使われている次の方法と相性がよくないです：
```
\directlua{
  local t = lua.get_functions_table();  t[#t + 1] = fn
  token.set_lua("CS", #t)
}
```
上記単独ではうまくいくのですが，`\newluafunction` で使われている「どこまで使用済みかを示すカウンタ」の値が更新されません．そのため，この後に `\newluafunction` したとき，同じ番号が割り当てられてしまいます．

**Comment by h-kitagawa** [comment]
とりあえず対症療法として https://github.com/luatexja/luatexja/commit/62ffb56df1dcfa53aa0df0ea0a1ab574bfb2f173 を書きました．

**Comment by h-kitagawa** [comment]
> とりあえず対症療法として [62ffb56](https://github.com/luatexja/luatexja/commit/62ffb56df1dcfa53aa0df0ea0a1ab574bfb2f173) を書きました．

これを入れた 20240505.0 を出しました．今はクローズしますが，根本的な解決ではないので何かあったら再オープンしてください．
