### ISSUE TITLE
luatexja-fontspec の Undefined control sequence

### ISSUE THREAD

**Issue by kmaed** [luatexja/luatexja#6]
TeX Live のアップデート後，
```
\documentclass{minimal}
\usepackage{luatexja-fontspec}
\begin{document}
\jfontspec{IPAMincho}
\end{document}
```
で次のエラーが出るようになりました．
```
! Undefined control sequence.
\__ltj_fontspec_setup_single_size:nnn ...nown:nxN
                                                  {fontspec-sizing}{\exp_aft...
```

どうやら {fontspec-luatex}{2024/05/03}{2.9c} で従来あった `\cs_generate_variant:Nn \keys_set_known:nnN {nx}` が削除されたようです．fontspec の変更にしたがうと，とりあえず2箇所ある `\keys_set_known:nxN` を `\keys_set_known:neN` に変更すればよいように思われます．

**Comment by h-kitagawa** [comment]
確認しました．https://github.com/latex3/fontspec/commit/95be0dfa5ba7a633ee87ea4a20547d9fd0dcb1f0 ですね．なんとかします．

**Comment by h-kitagawa** [comment]
https://github.com/luatexja/luatexja/commit/23f6f9b2872de62a7787c4aeb4240309adc984bf で "x-type" の引数を取る命令をできるだけ "e-type" のものに変更しました．

**Comment by kmaed** [comment]
試したところ，今度は lltjp-unicode-math がエラーを出すようです．
```
\documentclass{minimal}
\usepackage{luatexja}
\usepackage{unicode-math}
\setmathfont{TeX Gyre Termes Math}
\begin{document}
\end{document}
```
で
```
! Undefined control sequence.
<argument> \exp_last_unbraced:NNe
                       \cs_gset_eq:NN \mathoctothorpe {\char_generate:nn {"0002
```

**Comment by h-kitagawa** [comment]
おっと，`\exp_last_unbraced:NNx` は LaTeX3 でなく，unicode-math で定義されているのですね．lltjp-unicode-math.sty を直しました．

**Comment by kmaed** [comment]
今度は大丈夫そうです．ありがとうございました．

**Comment by h-kitagawa** [comment]
20240505.0 を出したので，完了とします．

**Comment by clerkma** [comment]
With a trace to commit [fontspec: minor simplification to size feature code](https://github.com/latex3/fontspec/commit/0e4eac9f79cf297f57ac5499fc0ab7abfe198637) (2024/05/11), line 230 of `luatexja-fontspec-29c.sty` should be updated from
```latex
    \__fontspec_setup_nfss:Nnnn \l__fontspec_nfss_tl {#1} {#2} {}
```
to
```latex
    \__fontspec_setup_nfss:Nn \l__fontspec_nfss_tl { #1 , #2 }
```

**Comment by h-kitagawa** [comment]
> With a trace to commit [fontspec: minor simplification to size feature code](https://github.com/latex3/fontspec/commit/0e4eac9f79cf297f57ac5499fc0ab7abfe198637) (2024/05/11)

Thank you very much. I hope that https://github.com/luatexja/luatexja/commit/a53bef337ee0cc4582e236e3642e4f31b9131e23 works.

**Comment by h-kitagawa** [comment]
I released the version 20240514.0.
