### ISSUE TITLE
LuaLaTeX で CJKの改行規則のminimum対応

### ISSUE THREAD

**Issue by t-tk** [luatexja/luatexja#7]
polyglossia の話題です。
[Missing line breaking for CJK in LuaLaTeX](https://github.com/reutenauer/polyglossia/issues/635)
LuaLaTeX + polyglossia で CJK 言語を使おうとしたとき、漢字と漢字の間のline breakを可能にしたいが、最低限の設定で出来ないか? という課題です。

XeLaTeX では、
```
 \XeTeXlinebreaklocale "ja" 
 \XeTeXlinebreakskip=0em plus 0.1em minus 0.01em 
```
のように設定すれば一応できます。
LuaLaTeX の場合、`luatexja-fontspec` を読み込むと、副作用がいろいろ多いとのことです。
`polyglossia-korean` を読み込む対策が示されていますが、何かいい方法は考えられるでしょうか?

**Comment by h-kitagawa** [comment]
ぜんぜん追えていなくてすみません．
> luatexja-fontspec を読み込むと、副作用がいろいろ多い

これはその通りですね．いくらかは対応できますが：
- 標準の和文文字/欧文文字の分別（U+201C など）が和文向きになっている→`\ltjsetparameter{jacharrange={...}}` でいじれる．
- 標準で和文フォントが 0.962216 倍→`\def\Cjascale{1}`

本当に「whatsit 等を無視した最小限」で良いのであれば，`polyglossia-korean.lua`（や，LuaTeX-ja より前の https://okumuralab.org/tex/mod/forum/discuss.php?d=627 あたりのもの）をベースに作った方が楽なのかもしれません．

ただ，polyglossia + LuaTeX-ja というケースもあることを考えると，どうすれば良いか悩ましいです．「TeX 側からは `\ltjsetparameter` 等の LuaTeX-ja と同じ命令を使いつつ，Lua による実装は全くの別物」とすると違和感は減るのでしょうか．

**Comment by t-tk** [comment]
コメントありがとうございます。
私がぼおっと眺めている印象では
Lua(La)TeX の CJK 対応は、日本語の LuaTeX-ja, 中国語の xeCJK, 韓国語の koTeX と各言語でばらばらに開発され、
`\XeTeXlinebreaklocale` や `\XeTeXlinebreakskip` に相当するものが存在しない、という風に受け止めています。

polyglossiaの方の議論では、`polyglossia-korean` を polyglossia-CJK-spacing に rename する案も出ているようです。
がっつりCJKの各言語に特化したものではなくても、ベースが非CJKの文書にパラグラフ程度ごとの範囲で CJKを入れたいニーズもあると思います。なので、機能を絞った簡単なものだけあるとよい、というイメージはあります。
確かに、LuaTeX-ja の開発初期の頃の検討は参考になりそうだ、と理解しました。

あとは、作る元気があるか、ですが、いつかやってみたいですが…。
ここは閉じておきます。
